import { IUserStore } from "@store/user.store";

export const paidUserStore: IUserStore = {
  user: {
    id: "mem_sb_clh97u67k00yh0ujrfxrja6l0",
    verified: false,
    createdAt: "2023-05-04T14:21:46.354Z",
    profileImage:
      "https://lh3.googleusercontent.com/a/AAcHTtdr_H_3_dvwTVX1MJcsTlI3T6Z-J6sGDexu-IsvRxPQ4Ro=s96-c",
    auth: {
      email: "william@ordotype.fr",
      hasPassword: true,
      providers: [
        {
          provider: "google",
        },
      ],
    },
    metaData: {},
    customFields: {
      nom: "grqe",
      phone: "03 20 06 38 22",
      prnom: "grqe",
      siret: "",
      "n-rpps": "Pas de RPPS",
      statut: "Medecin",
      "vat-id": "",
      country: "",
      semestre: "8",
      specialite: "Cardiologie",
      "date-de-switch": "2023-09-20",
      "mode-dexercice": "Remplacant",
      "partnership-city": "Service de Santé des Armées",
    },
    permissions: [],
    stripeCustomerId: "cus_OZn1gulIDVkUdX",
    loginRedirect: "/membership/successful-login",
    planConnections: [
      {
        id: "con_sb_cltprxaim0grs0ssyh9sw0etu",
        active: true,
        status: "ACTIVE",
        planId: "pln_soins-palliatifs-paid-plan-6tc60az6",
        type: "SUBSCRIPTION",
        payment: {
          priceId: "prc_soins-palliatifs-full-price-491be0t42",
          amount: 10,
          currency: "eur",
          status: "PAID",
          lastBillingDate: 1710332687,
          nextBillingDate: 1718281485,
          cancelAtDate: null,
        },
      },
      {
        id: "con_sb_clwhzg89a00b30sr04ikh3s7v",
        active: true,
        status: "ACTIVE",
        planId: "pln_udr-zp8u06dg",
        type: "FREE",
        payment: null,
      },
      {
        id: "con_sb_clwot9qv601p00smlclvkc6mp",
        active: false,
        status: "CANCELED",
        planId: "pln_module-rhumatologie-kei40zul",
        type: "SUBSCRIPTION",
        payment: {
          priceId: "prc_rhumatologie-discount-interne-6cow0xa7",
          amount: 1,
          currency: "eur",
          status: "PAID",
          lastBillingDate: 1716804828,
          nextBillingDate: null,
          cancelAtDate: null,
        },
      },
      {
        id: "con_sb_clwp3ykzh00920tr0g0z26qdi",
        active: true,
        status: "ACTIVE",
        planId: "pln_interne-m-decine-g-n-rale-adh-rent--4a4t0o95",
        type: "FREE",
        payment: null,
      },
      {
        id: "con_sb_clvf49qen00mc0swj13g5axcc",
        active: true,
        status: "ACTIVE",
        planId: "pln_sant-sexuelle-free-plan-lpiy01f0",
        type: "FREE",
        payment: null,
      },
      {
        id: "con_sb_clvf49lr200ma0swjh5cz2jcg",
        active: true,
        status: "ACTIVE",
        planId: "pln_urgences-free-plan-ssvm0tak",
        type: "FREE",
        payment: null,
      },
      {
        id: "con_sb_clrp56rdp0x7j0tsh3f1l0ygo",
        active: false,
        status: "CANCELED",
        planId: "pln_compte-interne-sy4j0oft",
        type: "SUBSCRIPTION",
        payment: {
          priceId: "prc_compte-interne-15-jours-offerts-kl120wmg",
          amount: 5,
          currency: "eur",
          status: "PAID",
          lastBillingDate: 1705940933,
          nextBillingDate: null,
          cancelAtDate: null,
        },
      },
    ],
    // @ts-ignore
    _comments: {
      isModerator: false,
    },
  },
  isAuth: true,
  hasPaidSub: true,
  init() {},
};
